// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Bf6xfyHVl2JqF9ObxR2mCr0sOpritJY',
    appId: '1:256600743679:web:d22808b63daf740a9876ca',
    messagingSenderId: '256600743679',
    projectId: 'halencustomerapp',
    authDomain: 'halencustomerapp.firebaseapp.com',
    storageBucket: 'halencustomerapp.appspot.com',
    measurementId: 'G-EXSQZQ62K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMe3JDj0I-5hXyAOzcb23dS_mjaxs-uIw',
    appId: '1:578685640061:android:40523a40b1d853304d0014',
    messagingSenderId: '578685640061',
    projectId: 'velox-payments',
    storageBucket: 'velox-payments.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdA7QfGjQSHElBCAPU5hjo7F4OAF8FVQE',
    appId: '1:578685640061:ios:76922253dd47f4ae4d0014',
    messagingSenderId: '578685640061',
    projectId: 'velox-payments',
    storageBucket: 'velox-payments.appspot.com',

    iosClientId: '578685640061-111r03jdctho380hhlmnvoigmijfl2gc.apps.googleusercontent.com',
    iosBundleId: 'com.app.velox',
  );
}
