// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb, kReleaseMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALIUnSldoP4s_h866Fmx2h18w-FAjRfkA',
    appId: '1:23456483694:android:0861fffb6cb04ad9ef997f',
    messagingSenderId: '23456483694',
    projectId: 'redeo-f4c25',
    storageBucket: 'redeo-f4c25.appspot.com',
  );

  static FirebaseOptions ios =  FirebaseOptions(
    apiKey: 'AIzaSyBf90e9r4WfdFasQwi_DtjpqSWjRVbw9Ek',
    appId: '1:23456483694:ios:7a5e968fac0971a5ef997f',
    messagingSenderId: '23456483694',
    projectId: 'redeo-f4c25',
    storageBucket: 'redeo-f4c25.appspot.com',
    androidClientId:
    '23456483694-v1u3ljs9cbuhck4foma9tre4sl7iuui4.apps.googleusercontent.com',
    iosClientId:
    '23456483694-csjij8q1fb2jj21hlbboe8nivls8bfan.apps.googleusercontent.com',
    iosBundleId: 'com.jack.redeo',
  );
}
